"""empty message

Revision ID: 135e011ac27c
Revises: db5f9959cef7
Create Date: 2023-06-29 15:15:47.628382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135e011ac27c'
down_revision = 'db5f9959cef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('check',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('check',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
