"""empty message

Revision ID: 74421cc8bd78
Revises: 9cb70ab6c07b
Create Date: 2023-06-29 11:32:43.508819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74421cc8bd78'
down_revision = '9cb70ab6c07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentation',
    sa.Column('pptIdx', sa.Integer(), nullable=False),
    sa.Column('formIdx', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['formIdx'], ['form.formIdx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pptIdx')
    )
    op.create_table('script_only',
    sa.Column('scriptOnlyIdx', sa.Integer(), nullable=False),
    sa.Column('formIdx', sa.Integer(), nullable=True),
    sa.Column('script', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['formIdx'], ['form.formIdx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scriptOnlyIdx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('script_only')
    op.drop_table('presentation')
    # ### end Alembic commands ###
