"""empty message

Revision ID: b68ee7b56b99
Revises: ddd5b6cccf33
Create Date: 2023-06-29 11:40:35.393545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68ee7b56b99'
down_revision = 'ddd5b6cccf33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('imgIdx', sa.Integer(), nullable=False),
    sa.Column('pptIdx', sa.Integer(), nullable=True),
    sa.Column('pgNum', sa.Integer(), nullable=False),
    sa.Column('imgUrl', sa.Text(), nullable=False),
    sa.Column('script', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pptIdx'], ['presentation.pptIdx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('imgIdx')
    )
    op.create_table('keyword',
    sa.Column('keyIdx', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=45), nullable=False),
    sa.Column('imgIdx', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('scriptOnlyIdx', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['imgIdx'], ['image.imgIdx'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scriptOnlyIdx'], ['scriptonly.scriptOnlyIdx'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('keyIdx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword')
    op.drop_table('image')
    # ### end Alembic commands ###
